import type { Trace } from "./types";

/**
 * Three hand-built demo traces of a Researcher -> Analyst -> Writer agent swarm.
 * These make the product demo-proof: the UI is fully alive with zero API calls.
 *  - trace-success:  clean run, high eval score
 *  - trace-toolfail: Analyst calls Tavily with a malformed arg -> hard failure
 *  - trace-halluc:   run completes but Writer fabricates a stat -> low eval score
 */

const AGENTS = ["Researcher", "Analyst", "Writer"];

export const SEED_TRACES: Trace[] = [
  {
    id: "trace-success",
    title: "AI observability market scan",
    createdAt: new Date(Date.now() - 6 * 60000).toISOString(),
    task: "Find the 3 most-funded AI-agent observability startups in 2026 and summarize how each differentiates.",
    status: "ok",
    totalMs: 4900,
    totalCostUsd: 0.0031,
    totalTokens: 7420,
    agents: AGENTS,
    spans: [
      {
        id: "s1",
        parentId: null,
        agent: "Researcher",
        kind: "agent",
        name: "Researcher",
        status: "ok",
        startMs: 0,
        durationMs: 1800,
      },
      {
        id: "s1a",
        parentId: "s1",
        agent: "Researcher",
        kind: "llm",
        name: "gpt-4o-mini · plan",
        status: "ok",
        startMs: 0,
        durationMs: 400,
        tokensIn: 340,
        tokensOut: 95,
        costUsd: 0.0002,
        input:
          "You are the Researcher. Break the task into search queries.\nTASK: Find the 3 most-funded AI-agent observability startups in 2026.",
        output:
          "Plan:\n1. search 'AI agent observability startup funding 2026'\n2. search 'LangSmith Langfuse Arize funding round 2026'\n3. synthesize top 3 by total raised",
      },
      {
        id: "s1b",
        parentId: "s1",
        agent: "Researcher",
        kind: "tool",
        name: "tavily.search",
        status: "ok",
        startMs: 420,
        durationMs: 780,
        input: '{ "query": "AI agent observability startup funding 2026", "max_results": 5 }',
        output:
          "5 results · [1] LangSmith (LangChain) Series B $125M · [2] Langfuse seed+A $19M · [3] Arize AI Series C $70M · [4] Helicone seed $12M · [5] Fiddler $45M",
      },
      {
        id: "s1c",
        parentId: "s1",
        agent: "Researcher",
        kind: "llm",
        name: "gpt-4o-mini · synthesize",
        status: "ok",
        startMs: 1220,
        durationMs: 560,
        tokensIn: 820,
        tokensOut: 210,
        costUsd: 0.0005,
        input: "Summarize the raw search results into a candidate shortlist.",
        output:
          "Shortlist: LangSmith ($125M), Arize ($70M), Langfuse ($19M). Handing to Analyst for differentiation.",
      },
      {
        id: "s2",
        parentId: null,
        agent: "Analyst",
        kind: "agent",
        name: "Analyst",
        status: "ok",
        startMs: 1820,
        durationMs: 1580,
      },
      {
        id: "s2a",
        parentId: "s2",
        agent: "Analyst",
        kind: "llm",
        name: "gpt-4o-mini · analyze",
        status: "ok",
        startMs: 1840,
        durationMs: 760,
        tokensIn: 990,
        tokensOut: 260,
        costUsd: 0.0006,
        input: "Compare LangSmith, Arize, Langfuse on positioning and moat.",
        output:
          "LangSmith = deepest LangChain/LangGraph integration. Arize = ML-observability heritage + evals. Langfuse = open-source, OTel-native, self-hostable.",
      },
      {
        id: "s2b",
        parentId: "s2",
        agent: "Analyst",
        kind: "tool",
        name: "tavily.search",
        status: "ok",
        startMs: 2620,
        durationMs: 580,
        input: '{ "query": "Langfuse open source self-host OpenTelemetry 2026" }',
        output: "3 results confirming OTel-native, ClickHouse+Postgres self-host.",
      },
      {
        id: "s2c",
        parentId: "s2",
        agent: "Analyst",
        kind: "llm",
        name: "gpt-4o-mini · rank",
        status: "ok",
        startMs: 3220,
        durationMs: 160,
        tokensIn: 410,
        tokensOut: 120,
        costUsd: 0.0003,
        input: "Rank by differentiation clarity.",
        output: "Order: LangSmith, Langfuse, Arize.",
      },
      {
        id: "s3",
        parentId: null,
        agent: "Writer",
        kind: "agent",
        name: "Writer",
        status: "ok",
        startMs: 3420,
        durationMs: 1180,
      },
      {
        id: "s3a",
        parentId: "s3",
        agent: "Writer",
        kind: "llm",
        name: "gpt-4o-mini · draft",
        status: "ok",
        startMs: 3440,
        durationMs: 1120,
        tokensIn: 1180,
        tokensOut: 470,
        costUsd: 0.0008,
        input: "Write the final 3-bullet summary with funding + differentiation.",
        output:
          "• LangSmith ($125M) — deepest LangChain/LangGraph integration, node-level trace + replay.\n• Langfuse ($19M) — open-source, OpenTelemetry-native, fully self-hostable.\n• Arize ($70M) — ML-observability heritage, strongest eval rigor.",
      },
      {
        id: "s4",
        parentId: null,
        agent: "Judge",
        kind: "eval",
        name: "LLM-as-judge",
        status: "ok",
        startMs: 4600,
        durationMs: 300,
        input: "Grade the final answer for correctness and relevance.",
        output: "PASS — all three figures verifiable, differentiation accurate.",
      },
    ],
    eval: {
      overall: 92,
      correctness: 95,
      relevance: 90,
      reasoning:
        "All three startups and funding figures are consistent with the retrieved sources; differentiation claims are accurate and non-redundant.",
    },
  },

  {
    id: "trace-toolfail",
    title: "Competitor pricing pull (FAILED)",
    createdAt: new Date(Date.now() - 22 * 60000).toISOString(),
    task: "Pull current pricing tiers for the top 3 observability tools and build a comparison.",
    status: "error",
    totalMs: 3120,
    totalCostUsd: 0.0014,
    totalTokens: 3110,
    agents: AGENTS,
    spans: [
      {
        id: "f1",
        parentId: null,
        agent: "Researcher",
        kind: "agent",
        name: "Researcher",
        status: "ok",
        startMs: 0,
        durationMs: 1500,
      },
      {
        id: "f1a",
        parentId: "f1",
        agent: "Researcher",
        kind: "llm",
        name: "gpt-4o-mini · plan",
        status: "ok",
        startMs: 0,
        durationMs: 420,
        tokensIn: 300,
        tokensOut: 88,
        costUsd: 0.0002,
        input: "Plan pricing research for LangSmith, Langfuse, Arize.",
        output: "Search each vendor pricing page, extract tiers, hand to Analyst.",
      },
      {
        id: "f1b",
        parentId: "f1",
        agent: "Researcher",
        kind: "tool",
        name: "tavily.search",
        status: "ok",
        startMs: 440,
        durationMs: 900,
        input: '{ "query": "LangSmith Langfuse Arize pricing 2026" }',
        output: "3 pricing pages found with per-seat + usage tiers.",
      },
      {
        id: "f2",
        parentId: null,
        agent: "Analyst",
        kind: "agent",
        name: "Analyst",
        status: "error",
        startMs: 1520,
        durationMs: 1600,
      },
      {
        id: "f2a",
        parentId: "f2",
        agent: "Analyst",
        kind: "llm",
        name: "gpt-4o-mini · build-args",
        status: "ok",
        startMs: 1540,
        durationMs: 700,
        tokensIn: 640,
        tokensOut: 190,
        costUsd: 0.0004,
        input: "Construct a tavily.extract call to read each pricing page.",
        output:
          'Calling tool with: { "urls": "langsmith.com/pricing, langfuse.com/pricing" }  // NOTE: passed a string, not an array',
      },
      {
        id: "f2b",
        parentId: "f2",
        agent: "Analyst",
        kind: "tool",
        name: "tavily.extract",
        status: "error",
        startMs: 2260,
        durationMs: 860,
        input: '{ "urls": "langsmith.com/pricing, langfuse.com/pricing" }',
        output: "",
        error:
          "ValidationError: `urls` must be an array of strings, received string. The Analyst passed a comma-joined string instead of a list.",
        failureType: "bad_tool_arg",
      },
    ],
    eval: {
      overall: 0,
      correctness: 0,
      relevance: 0,
      reasoning:
        "Run aborted: Analyst passed `urls` as a comma-joined string to tavily.extract; the tool requires an array. No final answer produced.",
    },
  },

  {
    id: "trace-halluc",
    title: "Market size estimate (hallucinated)",
    createdAt: new Date(Date.now() - 41 * 60000).toISOString(),
    task: "Estimate the 2026 TAM for AI-agent observability and cite a source.",
    status: "ok",
    totalMs: 4200,
    totalCostUsd: 0.0022,
    totalTokens: 5010,
    agents: AGENTS,
    spans: [
      {
        id: "h1",
        parentId: null,
        agent: "Researcher",
        kind: "agent",
        name: "Researcher",
        status: "ok",
        startMs: 0,
        durationMs: 1500,
      },
      {
        id: "h1a",
        parentId: "h1",
        agent: "Researcher",
        kind: "tool",
        name: "tavily.search",
        status: "ok",
        startMs: 20,
        durationMs: 820,
        input: '{ "query": "AI observability market size TAM 2026" }',
        output:
          "Results discuss the broader observability market but no clean agent-observability TAM figure was found.",
      },
      {
        id: "h1b",
        parentId: "h1",
        agent: "Researcher",
        kind: "llm",
        name: "gpt-4o-mini · synthesize",
        status: "ok",
        startMs: 860,
        durationMs: 600,
        tokensIn: 780,
        tokensOut: 180,
        costUsd: 0.0005,
        input: "Summarize TAM evidence.",
        output:
          "No direct agent-observability TAM figure available; broader APM market ~$11B. Flagging low confidence.",
      },
      {
        id: "h2",
        parentId: null,
        agent: "Writer",
        kind: "agent",
        name: "Writer",
        status: "ok",
        startMs: 1520,
        durationMs: 2380,
      },
      {
        id: "h2a",
        parentId: "h2",
        agent: "Writer",
        kind: "llm",
        name: "gpt-4o-mini · draft",
        status: "ok",
        startMs: 1540,
        durationMs: 2340,
        tokensIn: 1350,
        tokensOut: 520,
        costUsd: 0.0009,
        input:
          "Write the TAM estimate with a citation. IMPORTANT: only use figures found by the Researcher.",
        output:
          "The 2026 TAM for AI-agent observability is $4.7B according to Gartner's 2026 AgentOps report. [FABRICATED: no such figure or report was in the retrieved context]",
        failureType: "hallucination",
      },
      {
        id: "h3",
        parentId: null,
        agent: "Judge",
        kind: "eval",
        name: "LLM-as-judge",
        status: "ok",
        startMs: 3900,
        durationMs: 300,
        input: "Verify the cited figure exists in the retrieved context.",
        output:
          "FAIL — the $4.7B figure and 'Gartner 2026 AgentOps report' do not appear in any retrieved source. Hallucinated citation.",
      },
    ],
    eval: {
      overall: 41,
      correctness: 25,
      relevance: 78,
      reasoning:
        "The Writer fabricated a specific TAM figure ($4.7B) and a non-existent Gartner report not present in the retrieved context. Relevant topic, but the core claim is unsupported.",
    },
  },
];
